const Menu = [
  {
    id: 1,
    image: "images/roti.jpg",
    name: "roti and egg",
    category: "breakfast",
    price: "20tk",
    description: "Thin Roti with Egg Omlet like Role  ",
  },

  {
    id: 2,
    image: "images/allupakoida.jpg",
    name: "allu pakoida",
    category: "evening",
    price: "20 tk",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 3,
    image: "images/corn.jpg",
    name: "corn",
    category: "breakfast",
    price: "10tk",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 4,
    image: "images/chola.jpg",
    name: "chola",
    category: "lunch",
    price: "50 tk",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 5,
    image: "images/pizza.jpg",
    name: "pizza",
    category: "evening",
    price: "80 tk",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 6,
    image: "images/nonvegthali.jpg",
    name: "Non-Veg Thali",
    category: "dinner",
    price: "180 tk",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 7,
    image: "images/sweet.jpg",
    name: "Sweets",
    category: "dinner",
    price: "60 tk",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 8,
    image: "images/rajmarice.jpg",
    name: "Rajma Rice",
    category: "lunch",
    price: "60 tk",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 9,
    image: "images/samosa.jpg",
    name: "samaso",
    category: "evening",
    price: "10₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 10,
    image: "images/samosa.jpg",
    name: "samaso",
    category: "timepass",
    price: "10 tk",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 11,
    image: "images/friedrice.jpg",
    name: "fried rice",
    category: "lunch",
    price: "120 tk",
    description: "Awesome test if you take this with beaf. ",
  },
];

export default Menu;
